### ISSUE TITLE
Is it working on M1 Mac?

### ISSUE THREAD

**Issue by rodhash** [pschmitt/tmux-ssh-split#11]
Hi

It seems to not be working for me, I found one past issue for Mac but it seems to be fixed by now.

I've installed successfully, so if running again prefix + I this is what I get:

```
Already installed "tmux-themepack"
Already installed "tmux-prefix-highlight"
Already installed "tmux-resurrect"
Already installed "tmux-ssh-split"
Already installed "tmux-jump"

TMUX environment reloaded.

Done, press ENTER to continue.
```

As for the settings I'm using this .. its a copy/paste from the README.

```
set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-fail "false"
set-option -g @ssh-split-no-env "false"
set-option -g @ssh-split-no-shell "false"
set-option -g @ssh-split-strip-cmd "true"
set-option -g @ssh-split-verbose "true"
set-option -g @ssh-split-debug "false"
set-option -g @ssh-split-h-key "|"
set-option -g @ssh-split-v-key "S"
set-option -g @ssh-split-w-key "C"

set -g @plugin 'pschmitt/tmux-ssh-split'
```

Pressing the Prefix + any of these 3 keys above while in a remote SSH connection, it opens up a new pane but locally and not in the remote SSH server.

Am I missing something?

**Comment by rodhash** [comment]
Here a recording

![sshSplitIssue](https://github.com/pschmitt/tmux-ssh-split/assets/29671981/8c78c61e-2d81-4845-a81a-70b7f2677bba)

**Comment by lslz627** [comment]
same me~ 

> Here a recording
> 
> ![sshSplitIssue](https://private-user-images.githubusercontent.com/29671981/268793607-8c78c61e-2d81-4845-a81a-70b7f2677bba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzODEsIm5iZiI6MTcwNjg5NDA4MSwicGF0aCI6Ii8yOTY3MTk4MS8yNjg3OTM2MDctOGM3OGM2MWUtMmQ4MS00ODQ1LWE4MWEtNzBiN2YyNjc3YmJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2Q2ZDM1MDg0MDM3NWRjM2Q3ZjczMWEzMGVlNGY2ZTc5ZmRjNmM2NDRkZTFkYzAyMzMyNTI2OTI3MmI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kssn9szSU_XlKa592HceeCyKX4EpilRn-NgPNlLdOfk) [ ![sshSplitIssue](https://private-user-images.githubusercontent.com/29671981/268793607-8c78c61e-2d81-4845-a81a-70b7f2677bba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzODEsIm5iZiI6MTcwNjg5NDA4MSwicGF0aCI6Ii8yOTY3MTk4MS8yNjg3OTM2MDctOGM3OGM2MWUtMmQ4MS00ODQ1LWE4MWEtNzBiN2YyNjc3YmJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2Q2ZDM1MDg0MDM3NWRjM2Q3ZjczMWEzMGVlNGY2ZTc5ZmRjNmM2NDRkZTFkYzAyMzMyNTI2OTI3MmI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kssn9szSU_XlKa592HceeCyKX4EpilRn-NgPNlLdOfk) ](https://private-user-images.githubusercontent.com/29671981/268793607-8c78c61e-2d81-4845-a81a-70b7f2677bba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzODEsIm5iZiI6MTcwNjg5NDA4MSwicGF0aCI6Ii8yOTY3MTk4MS8yNjg3OTM2MDctOGM3OGM2MWUtMmQ4MS00ODQ1LWE4MWEtNzBiN2YyNjc3YmJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2Q2ZDM1MDg0MDM3NWRjM2Q3ZjczMWEzMGVlNGY2ZTc5ZmRjNmM2NDRkZTFkYzAyMzMyNTI2OTI3MmI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kssn9szSU_XlKa592HceeCyKX4EpilRn-NgPNlLdOfk) [ ](https://private-user-images.githubusercontent.com/29671981/268793607-8c78c61e-2d81-4845-a81a-70b7f2677bba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzODEsIm5iZiI6MTcwNjg5NDA4MSwicGF0aCI6Ii8yOTY3MTk4MS8yNjg3OTM2MDctOGM3OGM2MWUtMmQ4MS00ODQ1LWE4MWEtNzBiN2YyNjc3YmJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2Q2ZDM1MDg0MDM3NWRjM2Q3ZjczMWEzMGVlNGY2ZTc5ZmRjNmM2NDRkZTFkYzAyMzMyNTI2OTI3MmI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kssn9szSU_XlKa592HceeCyKX4EpilRn-NgPNlLdOfk)

**Comment by lslz627** [comment]
> Here a recording
> 
> ![sshSplitIssue](https://private-user-images.githubusercontent.com/29671981/268793607-8c78c61e-2d81-4845-a81a-70b7f2677bba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzODEsIm5iZiI6MTcwNjg5NDA4MSwicGF0aCI6Ii8yOTY3MTk4MS8yNjg3OTM2MDctOGM3OGM2MWUtMmQ4MS00ODQ1LWE4MWEtNzBiN2YyNjc3YmJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2Q2ZDM1MDg0MDM3NWRjM2Q3ZjczMWEzMGVlNGY2ZTc5ZmRjNmM2NDRkZTFkYzAyMzMyNTI2OTI3MmI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kssn9szSU_XlKa592HceeCyKX4EpilRn-NgPNlLdOfk) [ ![sshSplitIssue](https://private-user-images.githubusercontent.com/29671981/268793607-8c78c61e-2d81-4845-a81a-70b7f2677bba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzODEsIm5iZiI6MTcwNjg5NDA4MSwicGF0aCI6Ii8yOTY3MTk4MS8yNjg3OTM2MDctOGM3OGM2MWUtMmQ4MS00ODQ1LWE4MWEtNzBiN2YyNjc3YmJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2Q2ZDM1MDg0MDM3NWRjM2Q3ZjczMWEzMGVlNGY2ZTc5ZmRjNmM2NDRkZTFkYzAyMzMyNTI2OTI3MmI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kssn9szSU_XlKa592HceeCyKX4EpilRn-NgPNlLdOfk) ](https://private-user-images.githubusercontent.com/29671981/268793607-8c78c61e-2d81-4845-a81a-70b7f2677bba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzODEsIm5iZiI6MTcwNjg5NDA4MSwicGF0aCI6Ii8yOTY3MTk4MS8yNjg3OTM2MDctOGM3OGM2MWUtMmQ4MS00ODQ1LWE4MWEtNzBiN2YyNjc3YmJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2Q2ZDM1MDg0MDM3NWRjM2Q3ZjczMWEzMGVlNGY2ZTc5ZmRjNmM2NDRkZTFkYzAyMzMyNTI2OTI3MmI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kssn9szSU_XlKa592HceeCyKX4EpilRn-NgPNlLdOfk) [ ](https://private-user-images.githubusercontent.com/29671981/268793607-8c78c61e-2d81-4845-a81a-70b7f2677bba.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzODEsIm5iZiI6MTcwNjg5NDA4MSwicGF0aCI6Ii8yOTY3MTk4MS8yNjg3OTM2MDctOGM3OGM2MWUtMmQ4MS00ODQ1LWE4MWEtNzBiN2YyNjc3YmJhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyM2Q2ZDM1MDg0MDM3NWRjM2Q3ZjczMWEzMGVlNGY2ZTc5ZmRjNmM2NDRkZTFkYzAyMzMyNTI2OTI3MmI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kssn9szSU_XlKa592HceeCyKX4EpilRn-NgPNlLdOfk)

same me~

**Comment by lslz627** [comment]
same me~

**Comment by pschmitt** [comment]
Since I don't own a Mac I would need to see  debug logs (set `@ssh-split-debug` to true).

**Comment by rodhash** [comment]
Surely I can help w/ that

Added the below lines but the file `/tmp/tmux-ssh-split.log` is not being generated:

```
    # ssh split
    set-option -g @ssh-split-keep-cwd "true"
    set-option -g @ssh-split-keep-remote-cwd "true"
    set-option -g @ssh-split-fail "false"
    set-option -g @ssh-split-no-env "false"
    set-option -g @ssh-split-no-shell "false"
    set-option -g @ssh-split-strip-cmd "true"
    set-option -g @ssh-split-verbose "true"
    set-option -g @ssh-split-debug "true"
    set-option -g @ssh-split-h-key "|"
    set-option -g @ssh-split-v-key "S"
    set-option -g @ssh-split-w-key "C"
    set -g @plugin 'pschmitt/tmux-ssh-split'
```

**Comment by pschmitt** [comment]
Do you have TMPDIR set by any chance?
Cause the logfile path respects that by default.

**Comment by pschmitt** [comment]
Also since you mention gcp, are you using regular ssh to connect to your instance? Cause wrappers wouldn't be supported (yet).

**Comment by rodhash** [comment]
> TMPDIR

Oh yeah I do have this variable set .. found the log file, here it is:

```
+ [[ -z '' ]]
+ SPLIT_ARGS+=(-e "TMUX_SSH_SPLIT=1")
++ get_ssh_command
++ local child_cmd
++ local pane_id
++ local pane_pid
+++ get_current_pane_id
+++ get_current_pane_info
+++ tmux display -p '#{pane_id} #{pane_pid}'
+++ awk '{ print $1 }'
++ pane_id=%9
+++ get_pane_pid_from_pane_id %9
+++ tmux list-panes -F '#{pane_id} #{pane_pid}'
+++ awk '/^%9 / { print $2}'
++ pane_pid=75937
++ [[ -z 75937 ]]
++ local host
++ get_child_cmds 75937
++ local pid=75937
++ read -r child_cmd
+++ uname -s
++ [[ Darwin == \D\a\r\w\i\n ]]
++ ps -o pid=,ppid=,command=
++ grep --color=never 75937
++ awk '{$1="";$2="";print $0}'
++ is_ssh_or_mosh_command -zsh
++ is_ssh_command -zsh
++ [[ -zsh =~ ^(auto)?ssh ]]
++ is_mosh_command -zsh
++ grep -qE '(mosh)|(mosh-client) '
++ return 0
++ read -r child_cmd
++ is_ssh_or_mosh_command '/usr/bin/ssh vm1'
++ is_ssh_command '/usr/bin/ssh vm1'
++ [[ /usr/bin/ssh vm1 =~ ^(auto)?ssh ]]
++ is_mosh_command '/usr/bin/ssh vm1'
++ grep -qE '(mosh)|(mosh-client) '
++ read -r child_cmd
++ return 1
+ SSH_COMMAND=
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ tmux split -c /Users/noob -h -e TMUX_SSH_SPLIT=1
+ exit 0
+ [[ -z '' ]]
+ SPLIT_ARGS+=(-e "TMUX_SSH_SPLIT=1")
++ get_ssh_command
++ local child_cmd
++ local pane_id
++ local pane_pid
+++ get_current_pane_id
+++ get_current_pane_info
+++ tmux display -p '#{pane_id} #{pane_pid}'
+++ awk '{ print $1 }'
++ pane_id=%0
+++ get_pane_pid_from_pane_id %0
+++ tmux list-panes -F '#{pane_id} #{pane_pid}'
+++ awk '/^%0 / { print $2}'
++ pane_pid=78488
++ [[ -z 78488 ]]
++ local host
++ get_child_cmds 78488
++ local pid=78488
++ read -r child_cmd
+++ uname -s
++ [[ Darwin == \D\a\r\w\i\n ]]
++ ps -o pid=,ppid=,command=
++ grep --color=never 78488
++ awk '{$1="";$2="";print $0}'
++ is_ssh_or_mosh_command -zsh
++ is_ssh_command -zsh
++ [[ -zsh =~ ^(auto)?ssh ]]
++ is_mosh_command -zsh
++ grep -qE '(mosh)|(mosh-client) '
++ return 0
++ read -r child_cmd
++ is_ssh_or_mosh_command '/usr/bin/ssh vm1'
++ is_ssh_command '/usr/bin/ssh vm1'
++ [[ /usr/bin/ssh vm1 =~ ^(auto)?ssh ]]
++ is_mosh_command '/usr/bin/ssh vm1'
++ grep -qE '(mosh)|(mosh-client) '
++ read -r child_cmd
++ return 1
+ SSH_COMMAND=
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ tmux split -c /Users/noob -h -e TMUX_SSH_SPLIT=1
+ exit 0
+ [[ -z '' ]]
+ SPLIT_ARGS+=(-e "TMUX_SSH_SPLIT=1")
++ get_ssh_command
++ local child_cmd
++ local pane_id
++ local pane_pid
+++ get_current_pane_id
+++ get_current_pane_info
+++ tmux display -p '#{pane_id} #{pane_pid}'
+++ awk '{ print $1 }'
++ pane_id=%0
+++ get_pane_pid_from_pane_id %0
+++ tmux list-panes -F '#{pane_id} #{pane_pid}'
+++ awk '/^%0 / { print $2}'
++ pane_pid=80416
++ [[ -z 80416 ]]
++ local host
++ get_child_cmds 80416
++ local pid=80416
++ read -r child_cmd
+++ uname -s
++ [[ Darwin == \D\a\r\w\i\n ]]
++ ps -o pid=,ppid=,command=
++ grep --color=never 80416
++ awk '{$1="";$2="";print $0}'
++ is_ssh_or_mosh_command -zsh
++ is_ssh_command -zsh
++ [[ -zsh =~ ^(auto)?ssh ]]
++ is_mosh_command -zsh
++ grep -qE '(mosh)|(mosh-client) '
++ return 0
++ read -r child_cmd
++ is_ssh_or_mosh_command '/usr/bin/ssh vm1'
++ is_ssh_command '/usr/bin/ssh vm1'
++ [[ /usr/bin/ssh vm1 =~ ^(auto)?ssh ]]
++ is_mosh_command '/usr/bin/ssh vm1'
++ grep -qE '(mosh)|(mosh-client) '
++ read -r child_cmd
++ return 1
+ SSH_COMMAND=
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ tmux split -c /Users/noob -h -e TMUX_SSH_SPLIT=1
+ exit 0

```

**Comment by rodhash** [comment]
> Also since you mention gcp, are you using regular ssh to connect to your instance? Cause wrappers wouldn't be supported (yet).

yep, just ssh. I also have SSH multiplexing set but the initial connection is just SSH.

**Comment by pschmitt** [comment]
Thanks for the logfile.

Should be a simple fix:

```
[[ "$1" =~ ^(auto)?ssh ]]
```

does not match `/usr/bin/ssh xxx`

**Comment by pschmitt** [comment]
Please try the latest main commit

**Comment by rodhash** [comment]
Awesome, it's working now
