### ISSUE TITLE
Can't split if ssh session was launched with port forwarding

### ISSUE THREAD

**Issue by ryan-caesar-ramos** [pschmitt/tmux-ssh-split#12]
If I ssh with something like `ssh {username}@{address} -L 8888:localhost:8888`, when I try splitting a pane I get

```
trap -- '' SIGTTIN
trap -- '' SIGTTOU
Bad local forwarding specification 'SendEnv=TMUX_SSH_SPLIT:localhost:SendEnv=TMUX_SSH_SPLIT'
```

Is this expected behavior?

**Comment by pschmitt** [comment]
Going out on a limb here: no, it's not :)

You're expecting to have it open a split with ssh, but without the `-L xxx`, right?

If so we need to explicitly remove the port forwarding args (`-L xxx`, `-R xxx` or `-D xxx` from the invoked command.

**Comment by ryan-caesar-ramos** [comment]
Thanks for the quick reply! Actually, it would have been convenient for me to have the split pane keep the `-L xxx` behavior intact, but tbh this area isn't exactly my forte so I'd understand if it's not possible or even recommended.

If I'm okay with having the new pane lose the port forwarding behavior, is there something I can do so I can at least have the initial pane keep the `-L xxx` functionality?

**Comment by pschmitt** [comment]
Forwarding the same port twice will just not work, at best your ssh client will ignore the flag (or just fail if `ExitOnForwardFailure` is enabled).

To fix/implement that behavior I would need a debug log (see the `@ssh-split-debug` option)

**Comment by ryan-caesar-ramos** [comment]
Thanks, I think I get it! If I'm understanding this correctly, if I

1. enter a tmux session
2. ssh into a different machine
3. split a pane using this plugin

what happens is that a new pane is created, which is immediately followed by an attempt to ssh into the same machine that was ssh'd into previously? Which is different from if I had just

1. ssh'd into a different machine
2. launched tmux from within that machine
3. split a pane

which would maintain port forwarding across all panes had I used ssh with `-L xxx`?

**Comment by pschmitt** [comment]
Yeah you only need to port-forward once. For as long as the ssh connection is up the forwarding will be in effect.

So if you:

```
you@local $ ssh -L 8080:localhost:80080 remote
you@remote $ tmux
```

You then should be able to access your forwarded service from within the remote tmux session anyway.

For that use case this here plugin is of no use. Splits will happen in the remote session.

This plugin only brings something to the table if you run a local tmux session and ssh from a pane ie:

```
you@local $ tmux
you@local $ ssh remote
# split
```

**Comment by ryan-caesar-ramos** [comment]
Thanks for the clarifications!
