### ISSUE TITLE
Breaks functionality of the plugin  tmux-current-pane-hostname.

### ISSUE THREAD

**Issue by stormsz** [pschmitt/tmux-ssh-split#3]
Hello.

[tmux-current-pane-hostname](https://github.com/soyuka/tmux-current-pane-hostname) is a plugin that replaces the **#H** functionality and also adds some news options. 

The goal of the plugin is to be able to tell the hostname of the machine your are ssh'ed into. So if you have 2 panes side by side and one is sshed, selecting that pane dynamically changes the **#H** value.

Using both plugins together breaks tmux-current-pane-hostname functionality on the new panes created by 
tmux-ssh-split. 

I have open a report on the  tmux-current-pane-hostname github and the author suggested to also open one here in hopes we could work together to see if we can find some kind of middle ground fix:
https://github.com/soyuka/tmux-current-pane-hostname/issues/14

Would love to hear your thought on it.

**Comment by pschmitt** [comment]
I'm not familiar with this plugin, but after briefly checking out the code I can tell this is definitely not a tmux-ssh-split issue.

tmux-current-pane-hostname does not correctly detect if the ssh command is running in the current pane.
It actually only works if ssh is run directly. But tmux-ssh-split does a bit more than just run `ssh HOST`.

The actual command spawned by tmux-ssh-split would be something like the following:

```shell
echo '🧙👉 Running "ssh HOST"'; trap /usr/bin/zsh EXIT INT; ssh HOST
```

Some pointers as to how to fix this:

- `tmux display-message -p "#{pane_current_command}"` ([HERE](https://github.com/soyuka/tmux-current-pane-hostname/blob/master/scripts/shared.sh#L98-L103)) will only return the name of the leading command (`bash` or `zsh` in our case).
- this needs to updated to something akin to [what I've implemented here](https://github.com/pschmitt/tmux-ssh-split/blob/313903aa0a8dc67e1e9664ac951616cce5123ed4/scripts/tmux-ssh-split.sh#L28-L51)
