### ISSUE TITLE
wrong path for script

### ISSUE THREAD

**Issue by kurktchiev** [pschmitt/tmux-ssh-split#4]
So i have installed the plugin and setup a binding, but when i go to run it, it throws an error: /scripts/tmux-ssh-splush -v returned 127

If i just do $HOME/.tmux/pugins/tmux-ssh-split/scripts/tmux-ssh-split.sh -v it will actually work, so I think whats happening is that the tmux part of the run is not actually detecting its working dir properly?

Why not use $TMUX_PLUGIN_MANAGER_PATH since if TPM is running... that should exist. instead of doing https://github.com/pschmitt/tmux-ssh-split/blob/cb25596ee24c425c6797220c1488f470e48bd4d1/ssh-split.tmux#L63

**Comment by kurktchiev** [comment]
Yeah i just did a quick test and replacing the line with `swd="$TMUX_PLUGIN_MANAGER_PATH/tmux-ssh-split/scripts/tmux-ssh-split.sh"` makes things work. Now cant say thats the cleanest way to do it... but at least confirmed thats what the problem was.

I am getting this on OS X 10.latest, havent tested it on OSX 11.latest with tmux 3.1c

**Comment by pschmitt** [comment]
I prefer not to depend too directly on TPM, otherwise you would *need* to use TPM for this script to work.

How does readlink actually behave on MacOS? 
What does `$(readlink -f "$(dirname "$0")")/scripts/tmux-ssh-split.sh` actually resolve to?

I will hunt around for a better cross-platform solution.

**Comment by kurktchiev** [comment]
looks like the `-f` doesnt exist in MacOS:
```
╭─ 12:08:06  ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔ 
╰─❯ $(readlink -f "$(dirname "$0")")/scripts/tmux-ssh-split.sh
dirname: illegal option -- z
usage: dirname path
readlink: illegal option -- f
usage: readlink [-n] [file ...]
zsh: no such file or directory: /scripts/tmux-ssh-split.sh
```

**Comment by pschmitt** [comment]
> looks like the -f doesnt exist in MacOS:

Thanks for the info!

@kurktchiev How about the following?

```bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
swd="${script_dir}/scripts/tmux-ssh-split.sh"
```

That seems to be what most other tmux plugins use to dermine the current script dir.

**Comment by kurktchiev** [comment]
well just firing it off on the CLI it produces:
```
╰─❯ cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
/Users/boris
```
Which obviously is not the right place. let me drop it in the script and see whats up

**Comment by pschmitt** [comment]
> well just firing it off on the CLI it produces:

That's normal. This BASH_SOURCE is only set when in a script.

**Comment by kurktchiev** [comment]
```
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
swd="${script_dir}/scripts/tmux-ssh-split.sh"
``` 

works as expected

**Comment by pschmitt** [comment]
:+1:
