### ISSUE TITLE
Add support for mosh

### ISSUE THREAD

**Issue by mikeslattery** [pschmitt/tmux-ssh-split#7]
In [scripts/tmux-ssh-split.sh](../blob/master/scripts/tmux-ssh-split.sh#32) check for process name of `mosh` as well as `ssh|autossh`.  See lines [32](../blob/master/scripts/tmux-ssh-split.sh#L32), [68](../blob/master/scripts/tmux-ssh-split.sh#L68), [190](../blob/master/scripts/tmux-ssh-split.sh#L190)

**Comment by pschmitt** [comment]
Sure, I don't use mosh personally. Would review a PR though :)
