### ISSUE TITLE
Feature request: keep_cwd option not working for remote splits

### ISSUE THREAD

**Issue by eggbean** [pschmitt/tmux-ssh-split#8]
I've been using this tmux plugin for a few months and it's been pretty useful, but during this time I have made several attempts to debug the `keep_cwd` option not working for me when splitting remote windows. I always end up at `$HOME`, which makes it a bit less useful.

I don't think it has anything to do with my shell configuration as I have disabled them on the remote host.

Any ideas?

**Comment by pschmitt** [comment]
Hm, the `keep_cwd` code is really simple. It's just using tmux' builtin `#{pane_current_path}`.
Maybe verify that this gets set correctly?

Also are you 100p sure you enabled the option correctly?

**Comment by eggbean** [comment]
Yes, I think I have. I've been using tmux for many years and this plugin for a few months. I normally have the same directory come up when splitting panes.

`set -g @ssh-split-keep-cwd "true"`

I've been trying to `set -x` on the plugin, but everything I tried to redirect the output to a log file hasn't worked. I'll look into it again a bit later.

**Comment by eggbean** [comment]
I also want to figure out a way to add a condition in my `.zlogin` so that it doesn't execute when the this plugin makes the ssh connection. (It's not anything in this file that causes the cwd problem.)

**Comment by pschmitt** [comment]
> I also want to figure out a way to add a condition in my .zlogin so that it doesn't execute when this plugin makes the ssh connection. (It's not anything in this file that causes the cwd problem). I might have to make a fork for this to pass a variable along with the ssh command.

Like the idea, I've just implemented it in 60fa4b1a918285a645bd24b0adff766a12a40a5f. You can now check for `TMUX_SSH_SPLIT=1` in your zshrc.

**Comment by eggbean** [comment]
Hey, thanks for that. It doesn't seem to work for me though?

```
­ƒºÖ­ƒæë Running "ssh -A bastet.mydomain.co.uk"
Last login: Fri Jun 23 17:24:31 2023 from 82.xx.xx.xxx
jason@bastet:~% env | grep -i tmux
TERM=tmux-256color
TMUX_PLUGIN_MANAGER_PATH=/home/jason/.local/share/tmux/plugins
```
I tried commenting everything I could in `~/.ssh/config` to see if it was anything like ssh multiplexing stopping it from working and even deleted the file completely for testing.

**Comment by pschmitt** [comment]
Well, this var is only set on a "local" split. I can try to find a way to do so for the "remote" split.

**Comment by eggbean** [comment]
Ah, yes if you could do that it would be really good. I have `.zlogin` do some neofetch stats when `[[ -z $TMUX ]]`,  but don't want to see it with these ssh-splits either.

I have had this set in my `tmux.conf` so that tmux always starts a non-login shell.

```
# Start a non-login shell
set -g default-command "${SHELL}"
```

**Comment by pschmitt** [comment]
I've added an option for debugging tmux-ssh-split in 9e7851a089430243723049ea9bfb4e472aa5af7b: `@ssh-split-debug`, which you can set to `true`. The debug logs get written to `/tmp/tmux-ssh-split.log`

> Ah, yes if you could do that it would be really good. I have `.zlogin` do some neofetch stats when `[[ -z $TMUX ]]`, but don't want to see it with these ssh-splits either.
> 
> I have had this set in my `tmux.conf` so that tmux always starts a non-login shell (so no need for local variable for me).
> 
> ```
> # Start a non-login shell
> set -g default-command "${SHELL}"
> ```

Setting `default-command` does seem odd to me. 
Did you set `default-shell` as well?

My `default-command` is empty and `default-shell` is set to my shell.

**Comment by pschmitt** [comment]
9873f4a973f46704a21131667c38f0188adeea1a should give you `TMUX_SSH_SPLIT=1` on remote splits.

Please note that this requires `TMUX_SSH_SPLIT` to be in `AcceptEnv`in the sshd config.

**Comment by eggbean** [comment]
> [9873f4a](https://github.com/pschmitt/tmux-ssh-split/commit/9873f4a973f46704a21131667c38f0188adeea1a) should give you `TMUX_SSH_SPLIT=1` on remote splits.
> 
> Please note that this requires `TMUX_SSH_SPLIT` to be in `AcceptEnv`in the sshd config.

Excellent, thanks for adding this. It's working fine here.

**Comment by eggbean** [comment]
> > ```
> > # Start a non-login shell
> > set -g default-command "${SHELL}"
> > ```
> 
> Setting `default-command` does seem odd to me. Did you set `default-shell` as well?
> 
> My `default-command` is empty and `default-shell` is set to my shell.

From looking at at the tmux manual, it seems that `default-shell` is only used by `default-command`. By default tmux uses the default shell which I set using cloud-init, so for me it seems better not to use `default-shell` as if zsh doesn't start it's a good indication that cloud-init, ansible or whatever is failing.

The reason I `set -g default-command "${SHELL}"` is because tmux windows/panes are always (for some weird reason) login-shells otherwise. This starts a non-login shell instead so that `~/.bash_profile` or `.zlogin` are not executed with every tmux shell.

**Comment by eggbean** [comment]
> I've added an option for debugging tmux-ssh-split in [9e7851a](https://github.com/pschmitt/tmux-ssh-split/commit/9e7851a089430243723049ea9bfb4e472aa5af7b): `@ssh-split-debug`, which you can set to `true`. The debug logs get written to `/tmp/tmux-ssh-split.log`
> 

Great. These are the last two lines of the log:

+ start_cmd='echo '\''🧙👉 Running "ssh osiris -o SendEnv=TMUX_SSH_SPLIT"'\''; ssh osiris -o SendEnv=TMUX_SSH_SPLIT'
+ tmux split -e TMUX_SSH_SPLIT=1 -c /home/jason/.dotfiles -h 'echo '\''🧙👉 Running "ssh osiris -o SendEnv=TMUX_SSH_SPLIT"'\''; ssh osiris -o SendEnv=TMUX_SSH_SPLIT'

The actual cwd was `~/.dotfiles/TESTDIR`, but no mention of that. `/home/jason/.dotfiles` is mentioned, but the new pane starts at `$HOME` every time.

Full log: http://sprunge.us/4gPaBg

**Comment by eggbean** [comment]
I noticed that the ssh command doesn't include the `-A` switch anymore, like it did in my earlier comment, but `ssh-add -l` still shows the keys in the new pane, so it's not a problem.

**Comment by pschmitt** [comment]
> > I've added an option for debugging tmux-ssh-split in [9e7851a](https://github.com/pschmitt/tmux-ssh-split/commit/9e7851a089430243723049ea9bfb4e472aa5af7b): `@ssh-split-debug`, which you can set to `true`. The debug logs get written to `/tmp/tmux-ssh-split.log`
> 
> Great. These are the last two lines of the log:
> 
> ```
> + start_cmd='echo '\''🧙👉 Running "ssh osiris -o SendEnv=TMUX_SSH_SPLIT"'\''; ssh osiris -o SendEnv=TMUX_SSH_SPLIT'
> + tmux split -e TMUX_SSH_SPLIT=1 -c /home/jason/.dotfiles -h 'echo '\''🧙👉 Running "ssh osiris -o SendEnv=TMUX_SSH_SPLIT"'\''; ssh osiris -o SendEnv=TMUX_SSH_SPLIT'
> ```
> 
> The actual cwd was `~/.dotfiles/TESTDIR`, but no mention of that. `/home/jason/.dotfiles` is mentioned, but the new pane starts at `$HOME` every time.
> 
> Full log: http://sprunge.us/4gPaBg

oh no. Was the issue you raised initially for remote splits cwd not being persisted? 
Ie `ssh myhost` then splitting and hoping that the new split will ssh and automagically cd into the same dir that you were on in the first pane.


Cause that just isn't implemented. I tried, but there is just no reliable straght-forward way of enabling this feature. cwd is only retained for local splits.

My past experiments are still in the main script: https://github.com/pschmitt/tmux-ssh-split/blob/c1ee3052c5620c2a0bdc236ae58e5d65d0687c21/scripts/tmux-ssh-split.sh#L274C1-L287C1

**Comment by pschmitt** [comment]
> I noticed that the ssh command doesn't include the `-A` switch anymore, like it did in my earlier comment, but `ssh-add -l` still shows the keys in the new pane, so it's not a problem.

that shouldn't happen - unless you set `@ssh-split-strip-cmd = true`. 

Are you sure that the ssh command contains that flag? 
Is `ssh -A` the actual command running in the pane? (`ps -o command= -g PANE_PID`)

**Comment by eggbean** [comment]
> oh no. Was the issue you raised initially for remote splits cwd not being persisted? Ie `ssh myhost` then splitting and hoping that the new split will ssh and automagically cd into the same dir that you were on in the first pane.
> 
> Cause that just isn't implemented. I tried, but there is just no reliable straght-forward way of enabling this feature. cwd is only retained for local splits.
> 
> My past experiments are still in the main script: https://github.com/pschmitt/tmux-ssh-split/blob/c1ee3052c5620c2a0bdc236ae58e5d65d0687c21/scripts/tmux-ssh-split.sh#L274C1-L287C1

I can understand the problem now. What about something like this?...

* The plugin makes a ssh-split with the `$TMUX_SSH_SPLIT` variable.
* A tmux hook (not sure which one yet) triggers a script which tests for `$TMUX_SSH_SPLIT` and then does `tmux last-pane` and makes `"#{pane_current_path}"` into a tmux #{@variable}.
* That variable is used to change directory in the new pane.

**Comment by pschmitt** [comment]
> > oh no. Was the issue you raised initially for remote splits cwd not being persisted? Ie `ssh myhost` then splitting and hoping that the new split will ssh and automagically cd into the same dir that you were on in the first pane.
> > 
> > Cause that just isn't implemented. I tried, but there is just no reliable straght-forward way of enabling this feature. cwd is only retained for local splits.
> > 
> > My past experiments are still in the main script: https://github.com/pschmitt/tmux-ssh-split/blob/c1ee3052c5620c2a0bdc236ae58e5d65d0687c21/scripts/tmux-ssh-split.sh#L274C1-L287C1
> 
> I can understand the problem now. What about something like this?...
> 
> * The plugin makes a ssh-split with the `$TMUX_SSH_SPLIT` variable.
> * A tmux hook (not sure which one yet) triggers a script which tests for `$TMUX_SSH_SPLIT` and then does `tmux last-pane` and makes `"#{pane_current_path}"` into a tmux `#{@variable}`.
> * That variable is used to change directory in the new pane.
> 

Sadly there is no tmux hook that would allow that. It's not a thing that tmux would ever be able to do.

The client process (ssh client) is not aware of the cwd of the process you might be running on the remote host. 

The only viable implementation I could imagine would be doing some very awkward stuff like *typing* in commands in the current pane that runs the ssh client  to get the pts dev that you would need to assess the cwd of the process. This will break if you happen to have vim open for example. Then to have your new ssh client (in the new pane) cd into the right dir one would need to know the shell to execute on the remote, ie. `ssh host 'sh - c "cd DIR; $SHELL"'` which will be very error-prone as well.

The ssh protocol just doesn't give us enough information to work with.

Another way of implementing this would require writing a custom ssh client that sends back the current cwd to the calling process, but that's vastly out of scope for a tmux plugin.

**Comment by pschmitt** [comment]
Aight. I didn't give up on this.

There's another way to implement this, but be warned: your mileage may vary.

This one works by parsing PS1. It will therefore only work if your  (remote) PS1 actively displays the path you are currently in. 

To enable the feature:
`@ssh-split-keep-remote-cwd=true`
